### ISSUE TITLE
Alternativa za mixin modelovanje uređaja

### ISSUE THREAD

**Issue by mladenactually** [mladenactually/Automatoes#2]
Trenutno, uređaji su modelovani kao mixin-i, tj. svaki uređaj je mala klasa koja nasleđuje više klasa u zavisnosti od ponašanja koja zadovoljava (npr. `Fridge` nasleđuje `ResourceAware`, `BaseDevice`, `Toggleable` i `TemperatureAdjustable`). Novi uređaj pravio bi se, na primer, ovako:
```python
class Xbox(BaseDevice, ResourceAware, Toggleable):
    pass
```
Pristup vrednosti potrošnje struje onda bi izgledao ovako:
```python
x = Xbox()
print(x.electricity)
```
Možda, (možda!) je bolje da se ovo realizuje dinamičkije. Postojala bi klasa `Device` koja bi kao svoje **atribute** imala različita ponašanja; `Toggleable`, `ResourceAware`, `TemperatureAdjustable` itd. bi i dalje postojale (verovatno sa izmenjenim imenima). Ne bi uopšte bilo potrebe za posebnim klasama za frižider, klimu itd. već bi se sve relevantne informacije čuvale u jednoj klasi. Ovako nekako:
```python
class Device:
    def __init__(self, name, toggle_settings, temperature_settings, resource_consumption):
        self.name = name
        self.toggle_settings = toggle_settings
        self.temperature_settings = temperature_settings
        self.resource_consumption = resource_consumption
        # ...
```
Koristila bi se ovako:
```python
x = Device('xbox', ToggleSettings(), None, ResourceConsumption(electricity=10))
print(x.resource_consumption.electricity)
```
što je malo više koda, ali ne zahteva milijardu klasa za milijardu uređaja i mislim čini lakše mapiranje na GUI klase. Takođe, konstruktor se lako može napisati tako da bude jednostavije konstruisati novi objekat. Oba pristupa imaju svoje prednosti i mane i treba održati temeljnu diskusiju o ispravnom pristupu.

**Comment by cigor99** [comment]
A ima li potrebe raditi tako sa Device, tj. kako mislis da bi to olaksalo mapiranje? Mislim da nema potrebe menjati, jer za nas projekat samo treba da prikazujemo podatke o uredjaju, da treba da dodajemo uredjaje onda bi morali tako. Ako sam dobro shvatio to se svodi samo na to da li ce nase klase za podesavanja biti nasledjene ili ce biti parametri

**Comment by mladenactually** [comment]
re: poslednja rečenica - tačno tako. Problem je u tome što nije jednostavno manipulisati klasama generalno ako ne svaki put moraš da pitaš od koga si sve nasleđena. Trenutno odmaram od algoritama pa sam sklopio kratak kodić koji demonstrira ono o čemu pričam ovde. Poslaću vam za koji minut.

**Comment by cigor99** [comment]
Mislim bolje je resenje ako imamo samo klasu Device, samo sta je nedostatak tu?

**Comment by mladenactually** [comment]
Nedostatak bi bio to što ne možemo da menjamo šta radi recimo `Toggleable`. Kada frižider nasleđuje tu klasu on može da baci override na neke njene metode. Ovako, kada imamo jednu klasu, to je ili nemoguće ili jako neprijatno.

**Comment by cigor99** [comment]
Aha, ali sve te metode treba da podese temperaturu ili jacinu ili tako nesto, onda nema potrebe za override jer je razlika samo u max i min vrednosti

**Comment by mladenactually** [comment]
Tačno. U većini slučajeva ne treba override i meni ne pada na pamet slučaj kada treba, ali možda smo samo prevideli nešto. To je jedan od razloga zašto mislim da je ovo možda bolja opcija. Još jedna stvar je da je ovako mnogo lakše konstruisati nove Device objekte (kao što sam demonstrirao u primeru koji sam vam poslao). Kako stvari sada stoje, morao bih prvo da napišem `fridge = Fridge()` pa onda tek liniju po liniju da postavljam razne atribute - ovako bi moglo sve odjednom.

**Comment by mladenactually** [comment]
Ako ćete još razloga, GUI je, ja mislim, deset puta lakši po ovom predlogu - imaćemo komponentu za svaku osobinu i samo ćemo kontrolisati da li je prikazana ili ne na osnovu toga da li ta instanca uređaja ima to podešavanje. Jedini razlog zašto sam skeptičan je to što sam za trenutno rešenje isto prvo rekao da rešava sve probleme i da je mnogo bolje i da treba da ga koristimo sto posto. Prosto, ne bih da se zaletimo ponovo.

**Comment by mladenactually** [comment]
U tom smislu, mislim da je za sada bolje da se fokusiramo na druge grupe klasa (korisnici itd.) a da u vidu imamo obe alternative, sa pozitivnim naglaskom na onu predloženu ovde i demonstriranu prototipom koji sam vam poslao. Kada budemo imali potpuniju sliku modela, moći ćemo da napravimo razumniju odluku.

**Comment by mladenactually** [comment]
Uostalom, jedino nam je dijagram klasa dovoljan da počnemo da zapravo pišemo kod. Ostale možemo razvijati paralelno sa njim.

**Comment by cigor99** [comment]
Video sam prototip i jasno mi je kako bi ovo islo. Neka onda ostane za sad ovako kako jeste dok ne zavrsimo ostale klase koje ne zavise od ovoga, ali mislim da na kraju ipak uradimo sve kao jednu klasu Device

**Comment by mladenactually** [comment]
Dogovoreno. Neka onda ipak ovaj issue ostane otvoren do kada budemo odlučili šta i kako ćemo.

**Comment by nenadicu** [comment]
Prebacili smo sve uredjaje u jednu klasu i dodali stanja.
