### ISSUE TITLE
Dodati atribute za minimalne i maksimalne vrednosti atributa za klase `TemperatureAdjustable` i `VolumeAdjustable`

### ISSUE THREAD

**Issue by mladenactually** [mladenactually/Automatoes#3]
Korisnik ne može podesiti, recimo, temperaturu na vrednost nižu od određene za dati uređaj (za rernu bi to bilo, šta znam, 100 stepeni?).

**Comment by cigor99** [comment]
Dodali smo atribute za ogranicavanje
