### ISSUE TITLE
Refaktorisati `VolumeAdjustable` u više različitih klasa

### ISSUE THREAD

**Issue by mladenactually** [mladenactually/Automatoes#4]
Mislim da `VolumeAdjustable` služi za previše stvari koje nisu nužno povezane. Možda bi bilo dobro da se razbije na više klasa u zavisnosti koji to **khm** _volume_ zapravo podešavamo (zvučni sistem vs. mikrotalasna vs. veš mašina itd.).

**Comment by cigor99** [comment]
Da li da uzmemo da koristimo Enum koji se koristi za FanSpeed za Microwave i promenimo naziv tog enuma i da to koristimo i kao jacinu mikrotalasne?

**Comment by nenadicu** [comment]
Po meni nije potrebno za WashingMachine da stavljamo volume uopste. Dovoljno je on/off. Jer ti ranije podesis masinu kad ubacis ves. A ovo sto je Igor napisao samo promenimo ime Enuma i koristimo ga za 2 stvari mi je skroz ok.

**Comment by nenadicu** [comment]
Po meni nije potrebno za WashingMachine da stavljamo volume uopste. Dovoljno je on/off. Jer ti ranije podesis masinu kad ubacis ves. A ovo sto je Igor napisao samo promenimo ime Enuma i koristimo ga za 2 stvari mi je skroz ok.

**Comment by mladenactually** [comment]
@nenadicu Nisam siguran. Istom logikom mogu da kažem i da mi je za rernu dovoljno on/off jer ću sam pre toga staviti pile u nju i namestiti temperaturu. U nekoj meri ima smisla, ali nema razloga da se ne iskoristi `VolumeAdjustable` / napravi nova enumeracija pošto ne predstavlja nikakav preteran posao.

@cigor99 Nisam siguran kako misliš to. Za mikrotalasnu je svakako potreban novi enum. Moja kod kuće na primer ima snagr 150, 300, 400, 600 i 800 što nije baš low, mid i high (doduše, moja mikrotalasna nije pametna + ima još dosta podešavanja za odlediti hranu itd.). Ipak, ne moramo modelovati sve karakteristike svega jer je ovo igračka od projekta, ali enumeracije su barem jednostavne.

**Comment by cigor99** [comment]
@mladenactually A sta si mislio da stavim za Enum MicrowavePower? Da stavim kao brojeve ili da napravimo isto neke nivoe kao za FanSpeed koji ce imati vrednost 150, 300, ...?

**Comment by nenadicu** [comment]
@mladenactually Gledaj po meni ulaziti toliko u tematiku je previse. Razumem ja sta ti pricas i hoces da postignes. Ali u ovoj nasoj igracki od projekta po meni je bitnije da ona vidi da ima opcija za menjanje snage. Koje su to tacno opcije to nije bitno.  Ona nece toliko ulaziti u detalje. Da pravimo Enume sa tim vrednostima koje ti spominjes meno iskreno ruzno i ne vidim poentu. Nije veliki posao, a opet zasto se zatrpavati istim.

**Comment by mladenactually** [comment]
@cigor99 Šta znam, ja bih tu na primer stavio vrednosti P_150, P_300 itd. Nije bitno koje su im vrednosti jer nikada nećemo pravu mikrotalasnu podešavati na tu snagu.

@nenadicu Svakako. Mislim da onda mešamo ne nužno povezane stvari, ali možemo na primer da preimenujemo `FanSpeed` u `Power` ili tako nešto, pa da onda to koristimo generalno za stvari kao što je mikrotalasna. To bi bilo okej.

**Comment by nenadicu** [comment]
@mladenactually Pa to smo nas dvojica prvobitno odradili. Moje misljenje je da je to dovoljno. Za WashingMachine mozemo dodati novi Enum tipa P_40, P60, P_90 i da mu dodamo novu klasu WashingMachineAdjustable u kojoj cemo imati atribut tipa tog Enuma.

**Comment by mladenactually** [comment]
Možemo. Što se mene tiče, ovaj issue je ovim rešen.

**Comment by cigor99** [comment]
Dodali smo novi Enum za temperaturu i klasu za podesavanja
