### ISSUE TITLE
Trenutne klase za podešavanja su previše specifične...

### ISSUE THREAD

**Issue by mladenactually** [mladenactually/Automatoes#6]
...i zbog toga imamo česte rasprave oko toga da li treba dodati šta znam `WashingMachineAdjustable` ili `MicrowaveAdjustable` ili ko zna šta još. Ne moramo da se svađamo oko toga: dovoljne su nam dve klase - `ContinuousScale` i `DiscreteScale`. `ContinuousScale` će od atributa da ima minimalnu i maksimalnu, kao i trenutnu vrednost (na primer sve temperature ili glasnoća zvučnog sistema), dok će `DiscreteScale` imati listu dozvoljenih vrednosti (za klimu 0, 1, 2 (tj. LOW, MID, HIGH), za veš mašinu 30, 60, 90, za mikrotalasnu 150, 300, 400, itd.). Tako izbegavamo milijardu klasa i usput povećavamo fleksibilnost klasa, jer možda nemaju sve mikrotalasne ista podešavanja jelte. Šta misli narod o ovome?

**Comment by cigor99** [comment]
To je dobro, sad cemo izmeniti da bude tako
