### ISSUE TITLE
Predlog za GUI

### ISSUE THREAD

**Issue by nenadicu** [mladenactually/Automatoes#7]
Evo jedan predlog kako moze gui da izgleda. @mladenactually ako imas neki predlog sta da promenimo, slobodno.

**Comment by cigor99** [comment]
![a626613c-cd28-4135-83e1-cd30d694bc81](https://user-images.githubusercontent.com/18477418/60296656-e4ec2900-9926-11e9-8cfb-7de191d5cc69.jpg)
![c3383b1e-8637-40a2-85ba-3c40b68efd6f](https://user-images.githubusercontent.com/18477418/60296658-e4ec2900-9926-11e9-8aae-11f50b7064f0.jpg)
![76754adb-cde1-4af9-ba82-57f4410507a1](https://user-images.githubusercontent.com/18477418/60296659-e4ec2900-9926-11e9-8a52-4dfdc11672db.jpg)

**Comment by mladenactually** [comment]
Hmm, okej, i ja sam slično zamišljao izgled interfejsa. Doduše, ja sam mislio da tabovi za uređaj ne budu tabovi nego dijalozi - na dvoklik na uređaj ili izbor iz liste otvori se novi prozorčić gde su informacije za dati uređaj i odgovarajuća podešavanja. Takođe, bilo bi dobro da npr. u gornjem levom uglu stavimo informacije o trenutno ulogovanom korisniku, kao i dugmiće ili padajući meni za odlogovati se.

**Comment by mladenactually** [comment]
I, šta treba da prestavlja prva slika (ovo nije uvreda samo bukvalno ne znam šta je)?

**Comment by cigor99** [comment]
Prva slika je kako izgleda padajuci meni uredjaja. Svejedno je da li je tab ili dijalog, u sustini samo se druga komponenta koristi, a mogu se dodati te informacije i za logout

**Comment by mladenactually** [comment]
Mislim da je dijalog jednostavniji i lakši za implementaciju - zbog toga sam dao taj predlog.
