### ISSUE TITLE
Realizacija privilegija u odnosu na tip korisnika

### ISSUE THREAD

**Issue by mladenactually** [mladenactually/Automatoes#8]
U odnosu na to koji tip korisnika je trenutno ulogovan, treba odobriti ili zabraniti određene akcije. Gost može samo da vidi stanje svakog uređaja, vlasnik može da menja stanje uređaja, šalje prijave o defektima dizajneru tj. projektantu kao i da ih pregleda, dok projektant može da gleda stanje uređaja, gleda prijave o defektima i da obeleži stvari kao popravljene (valjda?). Pitanje je - kako realizovati ovo? Kao neku dodatnu klasu? Koja će povezivati šta? Ili samo kao niz provera kada prikazujemo odgovarajući pogled (view) za neki uređaj - ako je trenutni korisnik gost onda onemogući promenu itd.

**Comment by cigor99** [comment]
Ja sam mislio da se u zavisnosti od tipa korisnika prikazuju razlicite mogucnosti

**Comment by mladenactually** [comment]
Naravno, ali pitanje koje se postavlja je - kako? Ja sam mislio da svaki korisnik ima instancu `Permission` klase, koja samo kaže da li ima pravo da piše, čita ili "popravlja". `Designer` bi imao `read=True, write=False, repair=True`, `Owner` bi imao `read=True, write=True, repair=False`, dok bi `Guest` imao `read=True, write=False, repair=False` i slično. Ovo je možda dovoljno dobro jer je za svakog korisnika eksplicitno definisano šta može a šta ne može da radi i prostim flipovanjem bita možemo reći okej sada gost iz nekog razloga može da menja temperaturu frižidera. Sa druge strane, ove privilegije su definisane sa strane korisnika, što znači da korisnici imaju ista prava za sve uređaje.

**Comment by mladenactually** [comment]
Imati ista prava za sve uređaje u suštini nije nikakav problem, pa mislim da je ovo na kraju dovoljno dobro rešenje (svakako mnogo bolje nego da direktno gledamo da li je korisnik gost, pa, ako jeste, prikažemo jednu stvar, a ako nije onda pitamo da li je vlasnik itd.).

**Comment by mladenactually** [comment]
Na kraju krajeva, naš sistem ne može biti beskonačno fleksibilan - čak je i bolje da neke stvari budu fiksirane.

**Comment by nenadicu** [comment]
To sto kazes, ne mozes biti fleksibilan do kraja. Ovo sa true i false je meni skroz korektan nacin da obezbedimo to.
